Issue #12 - Datum Registrace Organizace
cesko-digital/pomahejukrajine-contember pull request #21
Opened 2022-05-05 23:01 UTC by VanaMartin

Muj prvni commit do projektu, takze prosim o trpelivost, teprve se seznamuji.

PR pridava pole "dateRegistered" do organizace s defaultni hodnotou "now". Pokryva issue #12 alespon castecne. Z popisu nebylo jasne, zda by mela hodnota byt vyzadovana ve formulari, nebo generovana automaticky.

2022-05-07 14:28 UTC, honzasladek requested changes
@VanaMartin Protože to teď nastaví u všech založených datum na `now()`, tak navrhuju přidat do formuláře s editací organizace (`organizationForm.tsx`) i políčko na editaci toho datumu založení. Mělo by to být zhruba na jeden řádek: https://docs.contember.com/reference/admin/components/form-fields/#date-field

Dává smysl?

Jinak LGTM 👍

2022-05-07 17:58 UTC, ViliamV commented on admin/pages/organizations.tsx
> +        <DateCell field="dateRegistered" header="Datum Registrace" />
nitpick: indentation 😉

2022-05-07 18:10 UTC, VanaMartin commented on admin/pages/organizations.tsx
> +        <DateCell field="dateRegistered" header="Datum Registrace" />
:scream: jak se to mohlo stat!

2022-05-07 18:17 UTC, VanaMartin commented on admin/pages/organizations.tsx
> +        <DateCell field="dateRegistered" header="Datum Registrace" />
TAB vs. 4 spaces. Sila zvyku, opravim

2022-05-07 18:30 UTC, VanaMartin commented
> @VanaMartin Protože to teď nastaví u všech založených datum na `now()`, tak navrhuju přidat do formuláře s editací organizace (`organizationForm.tsx`) i políčko na editaci toho datumu založení. Mělo by to být zhruba na jeden řádek: https://docs.contember.com/reference/admin/components/form-fields/#date-field
> 
> Dává smysl?
> 
> Jinak LGTM +1

Jasne, pridano. Dejte vedet, pokud to mam mergnout.

2022-05-09 06:56 UTC, honzasladek approved these changes

2022-05-09 06:56 UTC, honzasladek commented
@VanaMartin Za mě 👍 a může se to mergnout.

2022-05-09 08:31 UTC, merged